apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
  namespace: notes-app
data:
  NODE_ENV: "production"
  PORT: "4000"
  CORS_ORIGIN: "http://localhost:3000"
  POSTGRES_DB: "notesdb"
  POSTGRES_USER: "notesuser"
  VITE_API_URL: "http://notes-backend-service:4000/api"
